[package]
name = "touying-qudeleap"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Yusheng Zhao <yushengzhao2020@outlook.com>"]
license = "MIT"
description = "Touying Slide Theme for QudeLeap"
repository = "https://github.com/QudeLeap/touying-qudeleap"
keywords = ["touying", "slide", "theme", "qudeleap"]
categories = ["presentation"]
exclude = [".github/", "examples/"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
